version: "3.9"

services:
  db:
    image: mysql:8
    container_name: studygroup-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Use port 3307 instead of 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    networks:
      - studygroup-network

  backend:
    build: 
      context: ./studygroup-backend
      dockerfile: Dockerfile
    container_name: studygroup-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - studygroup-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./studygroup-frontend
      dockerfile: Dockerfile
    container_name: studygroup-frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_SOCKET_URL: ${VITE_SOCKET_URL}
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - studygroup-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  studygroup-network:
    driver: bridge